name: job_portal_ui
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.0
  http: ^0.13.0
  file_picker: ^5.3.3
  image_picker: ^0.8.7+1
  cached_network_image: ^3.3.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/gawean_icon.png
    - assets/facebook_logo.png
    - assets/google_logo.webp
    - assets/gokab_icon.png
    - assets/airbnb_logo.png
    - assets/sample_photo_1.png
    - assets/sample_photo_2.png
    - assets/twitter_logo.png
    - assets/default_logo.png
    - assets/default_profile.png
    - assets/career_tips_bg.jpg
    - assets/minimalist_bg.png
    - assets/background1.jpg
