name: job_portal_ui
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.0.0
# followed by an optional build number separated by a +.
# Both the version and the build number can be overridden in flutter.yaml.
# In Android, build numbers are also used as version codes.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Ensures Dart SDK version 3.0.0 or higher is used

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.0 # Or the latest version available
  http: ^0.13.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of the editor configuration see
# https://dart.dev/tools/editor/configure-editor
flutter:
  uses-material-design: true
  assets:
    - assets/gawean_icon.png # Ensure this line is present and correctly indented
    - assets/facebook_logo.png
    - assets/google_logo.webp
    - assets/gokab_icon.png
    - assets/airbnb_logo.png
    - assets/sample_photo_1.png
    - assets/sample_photo_2.png
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
